## Server properties
server:
  port: 4002

## Spring properties
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@thoondevdb_medium?TNS_ADMIN=C:/Workspaces/tranings/spring-boot-practice/src/main/resources/Wallet
    username: admin
    password: Thnadm2023$$%

  jpa:
    database-platform: org.hibernate.dialect.Oracle19cDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true

#    driver-class-name: org.mariadb.jdbc.Driver
#    # 개발 서버용 DB
#    url: jdbc:mariadb://172.16.100.222:3306/aice_log?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
#    username: root
#    password: aidb!@34