## Server properties

## Spring properties
spring:
  config:
    activate:
      on-profile: practice

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    # 개발 서버용 DB
    url: jdbc:mariadb://172.16.100.222:3306/aice_log?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: aidb!@34
