## Server properties
server:
  port: 8989

## Spring properties
spring:
  application:
    name: practice

  profiles:
    active: local

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@thoondevdb_medium?TNS_ADMIN=./src/main/resources/Wallet/
    username: admin
    password: Thnadm2023$$%
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 10
      maximum-pool-size: 50
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      pool-name: pool-practice

  jpa:
    database-platform: org.hibernate.dialect.Oracle19cDialect
    properties:
      hibernate:
        format_sql: true
        hbm2ddl.auto: update
        implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    open-in-view: false
    show-sql: true

#    driver-class-name: org.mariadb.jdbc.Driver
#    # 개발 서버용 DB
#    url: jdbc:mariadb://172.16.100.222:3306/aice_log?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
#    username: root
#    password: aidb!@34
